"""Building one face for one page.

This is the part the rest of the product talks to. It takes a page, the
lettering on it and the characters the translation needs, and returns a font
file: the letters that could be lifted from the picture are the letters from
the picture, and the rest are the closest installed face bent to match them.

The honest limit is worth stating where the code is. English lettering contains
no Ж, and no amount of measuring four Latin letters produces the Ж the same
hand would have written — that one is derived, and derived means "a donor's Ж,
at this weight, this slant and this width". Where the source and the target
share an alphabet, or where the sample is a whole handwriting sheet, the
letters really are the sample's own.
"""

from __future__ import annotations

import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

from picglot.core.logging import get_logger
from picglot.foundry import build, donor, harvest, outlines
from picglot.foundry.outlines import GlyphImage
from picglot.vision import fonts

log = get_logger(__name__)

#: Below this many characters lifted from the page, tracing has not learnt
#: anything the donor does not already know, and the whole face is derived.
MIN_TRACED_TO_MATTER = 3

#: Characters a generated face carries beyond the ones asked for: without the
#: common punctuation a translated line falls back mid-sentence and the change
#: of face mid-line is more visible than a slightly wrong comma.
ALWAYS_INCLUDE = ".,!?:;'\"-—()«»„“”…"


@dataclass(slots=True)
class Sample:
    """One line of source text and where it sits on the page."""

    box: tuple[int, int, int, int]
    text: str


@dataclass(slots=True)
class SynthesisResult:
    data: bytes
    family: str
    traced: str = ""
    derived: str = ""
    donor_family: str | None = None
    metrics: dict[str, float] = field(default_factory=dict)

    def as_dict(self) -> dict[str, object]:
        return {
            "family": self.family,
            "traced": self.traced,
            "derived": self.derived,
            "donor_family": self.donor_family,
            "bytes": len(self.data),
        }


def synthesize(
    image: Image.Image,
    samples: list[Sample],
    *,
    characters: str,
    family: str,
    donor_path: str,
    donor_family: str | None = None,
    donor_index: int = 0,
    style: donor.StyleParameters | None = None,
) -> SynthesisResult | None:
    """Build a face covering ``characters`` in the style of ``samples``."""
    wanted = _wanted(characters)
    if not wanted:
        return None

    traced = _harvest(image, samples)
    # Tracing a couple of letters is not worth a mixed face: two letterforms
    # from the page beside forty from a donor reads as a mistake, not as
    # fidelity. Either the page taught us something or the donor does the work.
    if len(traced) < MIN_TRACED_TO_MATTER:
        traced = {}

    usable = {char: glyph for char, glyph in traced.items() if char in wanted}
    missing = "".join(sorted(wanted - set(usable)))
    derived = (
        donor.derive(missing, font_path=donor_path, font_index=donor_index, style=style)
        if missing
        else {}
    )

    glyphs = {**derived, **usable}  # a letter from the page always wins
    if not glyphs:
        return None

    outlines_by_char = {char: outlines.trace(glyph) for char, glyph in glyphs.items()}
    metrics = _metrics(glyphs)
    try:
        data = build.build_font(
            outlines_by_char,
            family=family,
            metrics=metrics,
            designer_note=(
                f"Generated by PicGlot: {len(usable)} letters traced from the page, "
                f"{len(derived)} derived from {donor_family or 'an installed face'}."
            ),
        )
    except Exception as error:  # pragma: no cover - defensive
        log.warning("foundry.build_failed", family=family, error=str(error)[:160])
        return None

    return SynthesisResult(
        data=data,
        family=family,
        traced="".join(sorted(usable)),
        derived="".join(sorted(derived)),
        donor_family=donor_family,
        metrics={"ascent": float(metrics.ascent), "descent": float(metrics.descent)},
    )


def _wanted(characters: str) -> set[str]:
    return {
        char
        for char in set(characters) | set(ALWAYS_INCLUDE)
        if not char.isspace() and char.isprintable()
    }


def _harvest(image: Image.Image, samples: list[Sample]) -> dict[str, GlyphImage]:
    """Every letter the page will give up, at the scale it was written at.

    Samples come from different lines at different sizes, and a glyph carries
    the size it was cut at, so the outlines land on a common em regardless.
    """
    collected: dict[str, GlyphImage] = {}
    for sample in samples:
        line = harvest.harvest_line(image, sample.box, sample.text)
        if line is None:
            continue
        for char, glyph in line.glyphs.items():
            collected.setdefault(char, glyph)
    return collected


def _metrics(glyphs: dict[str, GlyphImage]) -> build.FontMetrics:
    """Vertical metrics from the letters themselves, in font units."""
    metrics = build.FontMetrics()
    heights: list[float] = []
    depths: list[float] = []
    for glyph in glyphs.values():
        scale = metrics.units_per_em / max(1.0, glyph.em_pixels)
        heights.append(glyph.baseline * scale)
        depths.append((glyph.mask.shape[0] - glyph.baseline) * scale)
    if heights:
        metrics.ascent = max(metrics.ascent, int(max(heights)))
    if depths:
        metrics.descent = max(metrics.descent, int(max(depths)))
    return metrics


# --------------------------------------------------------------------------- #
# Putting a generated face where the renderer can find it
# --------------------------------------------------------------------------- #
def materialize(data: bytes, name: str) -> Path | None:
    """Write a font to disk and register it, so the renderer can select it.

    The renderer reaches fonts through the registry, which is built by scanning
    directories at startup — a face generated for one job was never in one.
    Writing it into a cache directory and registering it there is what makes it
    selectable by the ordinary path, coverage checks and all, rather than
    needing a second way to load a font.
    """
    directory = Path(tempfile.gettempdir()) / "picglot-fonts"
    try:
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{name}.ttf"
        path.write_bytes(data)
    except OSError as error:  # pragma: no cover - full or read-only disk
        log.warning("foundry.materialize_failed", error=str(error)[:160])
        return None
    return path if fonts.registry.register(path) else None
