"""Initial schema.

The first revision materialises the schema directly from the SQLAlchemy models
so the database can never drift from the code on a fresh install. Every later
revision is a normal autogenerated diff against this baseline
(``alembic revision --autogenerate``). See
docs/architecture-decisions/0004-migrations-from-models.md.

Revision ID: 0001
Revises:
Created: 2026-08-02
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from lingoimage.db.base import Base
from lingoimage.db import models  # noqa: F401  (registers the tables)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind, checkfirst=True)

    if bind.dialect.name == "postgresql":
        # Case-insensitive search on project names in the dashboard.
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_projects_name_trgm "
            "ON projects USING gin (name gin_trgm_ops)"
        )
        # Only unfinished jobs are ever scanned by the queue sweeper.
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_jobs_active "
            "ON jobs (priority DESC, created_at) "
            "WHERE status IN ('created','queued','preprocessing','detecting',"
            "'recognizing','translating','inpainting','rendering','exporting')"
        )
        # Retention sweeps only look at rows that can actually expire.
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_assets_expiring "
            "ON assets (expires_at) WHERE expires_at IS NOT NULL"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_webhook_deliveries_due "
            "ON webhook_deliveries (next_attempt_at) "
            "WHERE status = 'failed' AND next_attempt_at IS NOT NULL"
        )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for index in (
            "ix_projects_name_trgm",
            "ix_jobs_active",
            "ix_assets_expiring",
            "ix_webhook_deliveries_due",
        ):
            op.execute(f"DROP INDEX IF EXISTS {index}")
    Base.metadata.drop_all(bind=bind)
