#!/usr/bin/env bash
# LingoImage AI — server survey.
#
# Read-only: collects facts about what is already running on this machine so a
# new deployment can be planned without colliding with existing projects.
# Changes nothing, installs nothing, starts nothing.
#
# Usage:
#   curl -fsSL <url>/server-diagnostics.sh -o /tmp/diag.sh && bash /tmp/diag.sh
# or, if you already have the repo on the server:
#   bash scripts/server-diagnostics.sh > diag-report.txt 2>&1
#
# Some sections need root to see everything; run under sudo for the fullest
# picture. Without sudo it still works, it just reports less.

set -uo pipefail

h() { printf '\n\n========== %s ==========\n' "$1"; }
have() { command -v "$1" >/dev/null 2>&1; }
try() { "$@" 2>&1 | head -n "${HEAD_N:-40}" || echo "(command failed or not permitted)"; }

echo "LingoImage AI server diagnostics — $(date -u '+%Y-%m-%d %H:%M:%SZ')"
echo "Report generated by scripts/server-diagnostics.sh"

h "1. Host"
try uname -a
[ -f /etc/os-release ] && try cat /etc/os-release
echo "--- uptime ---"; try uptime
echo "--- who am i ---"; echo "user=$(id -un) uid=$(id -u) groups=$(id -Gn)"

h "2. CPU / RAM / load"
if have lscpu; then try lscpu | grep -E 'Model name|^CPU\(s\)|Thread|Core|Socket|MHz'; fi
echo "--- memory ---"; try free -h
echo "--- swap ---"; try swapon --show

h "3. Disk"
HEAD_N=30 try df -hT -x tmpfs -x devtmpfs
echo "--- largest dirs under /var, /opt, /home (may take a moment) ---"
HEAD_N=15 try du -xh --max-depth=2 /var /opt /home 2>/dev/null | sort -rh

h "4. Docker"
if have docker; then
  try docker version --format 'client={{.Client.Version}} server={{.Server.Version}}'
  echo "--- compose plugin ---"; try docker compose version
  echo "--- running containers ---"
  HEAD_N=60 try docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'
  echo "--- all containers (incl. stopped) ---"
  HEAD_N=60 try docker ps -a --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
  echo "--- compose projects ---"
  HEAD_N=30 try docker compose ls -a
  echo "--- networks ---"; HEAD_N=30 try docker network ls
  echo "--- volumes ---"; HEAD_N=40 try docker volume ls
  echo "--- disk usage ---"; try docker system df
else
  echo "docker: NOT INSTALLED"
fi

h "5. Listening ports (what a new deployment must avoid)"
if have ss; then
  HEAD_N=60 try ss -tulpn
elif have netstat; then
  HEAD_N=60 try netstat -tulpn
else
  echo "neither ss nor netstat available"
fi
echo "--- specifically: ports this project wants ---"
for port in 80 443 3000 8000 5432 6379 9000 9001 8025 9090 3001; do
  if have ss; then
    inuse=$(ss -tulpn 2>/dev/null | awk -v p=":${port}\$" '$5 ~ p {print $1, $5, $7}' | head -3)
  else
    inuse=""
  fi
  if [ -n "${inuse}" ]; then
    echo "  ${port}: IN USE -> ${inuse}"
  else
    echo "  ${port}: free (or not visible without root)"
  fi
done

h "6. Reverse proxy / web server"
for svc in nginx apache2 httpd caddy traefik haproxy; do
  if have "$svc"; then echo "FOUND binary: $svc ($($svc -v 2>&1 | head -1))"; fi
done
if have systemctl; then
  echo "--- proxy-ish services ---"
  HEAD_N=25 try systemctl list-units --type=service --state=running --no-pager --no-legend \
    | grep -Ei 'nginx|apache|httpd|caddy|traefik|haproxy'
fi
echo "--- nginx sites (names only; contents not dumped, they may hold secrets) ---"
for d in /etc/nginx/sites-enabled /etc/nginx/conf.d /etc/caddy /etc/apache2/sites-enabled; do
  [ -d "$d" ] && { echo "  $d:"; ls -1 "$d" 2>/dev/null | sed 's/^/    /'; }
done
echo "--- server_name / domain directives found (hostnames only) ---"
HEAD_N=40 try grep -rhoE '^[[:space:]]*server_name[[:space:]]+[^;]+' /etc/nginx 2>/dev/null

h "7. TLS certificates"
if have certbot; then
  HEAD_N=40 try certbot certificates
else
  echo "certbot: not installed"
fi
[ -d /etc/letsencrypt/live ] && { echo "--- /etc/letsencrypt/live ---"; try ls -1 /etc/letsencrypt/live; }

h "8. Databases already on this host"
for svc in postgresql mysql mariadb redis-server mongod; do
  if have systemctl; then
    state=$(systemctl is-active "$svc" 2>/dev/null)
    [ -n "$state" ] && [ "$state" != "unknown" ] && echo "  ${svc}: ${state}"
  fi
done
have psql && echo "  psql client: $(psql --version)"
have redis-cli && echo "  redis-cli: $(redis-cli --version)"

h "9. Runtimes"
for bin in python3 node npm git make; do
  if have "$bin"; then echo "  ${bin}: $($bin --version 2>&1 | head -1)"; else echo "  ${bin}: absent"; fi
done

h "10. Firewall"
if have ufw; then try ufw status verbose; fi
if have firewall-cmd; then try firewall-cmd --list-all; fi
if have iptables; then echo "--- iptables INPUT ---"; HEAD_N=25 try iptables -S INPUT; fi

h "11. Existing LingoImage install (if any)"
for d in /opt/lingoimage /srv/lingoimage /home/*/lingoimage* /var/www/lingoimage*; do
  [ -d "$d" ] && { echo "  found: $d"; ls -la "$d" 2>/dev/null | head -15; }
done

h "12. Systemd services (non-default, running)"
if have systemctl; then
  HEAD_N=50 try systemctl list-units --type=service --state=running --no-pager --no-legend
fi

h "13. Cron"
try crontab -l
[ -d /etc/cron.d ] && { echo "--- /etc/cron.d ---"; try ls -1 /etc/cron.d; }

h "14. Outbound connectivity (needed for image pulls / provider APIs)"
for target in registry-1.docker.io github.com api.deepl.com; do
  if have curl; then
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 6 "https://${target}" 2>/dev/null)
    echo "  https://${target} -> HTTP ${code:-no-response}"
  fi
done

h "15. Public IP / DNS"
if have curl; then
  echo "  public IPv4: $(curl -s --max-time 6 https://api.ipify.org 2>/dev/null || echo unknown)"
fi
have hostname && echo "  hostname: $(hostname -f 2>/dev/null || hostname)"

echo
echo
echo "========== END OF REPORT =========="
echo "Nothing was modified. Paste this whole output back to plan the deployment."
echo
echo "NOTE: this report can contain hostnames, IPs and service names. It does"
echo "NOT dump config file contents, .env files, keys or certificates — but"
echo "skim it before sharing publicly."
